# Top 5 interesting Torch functions to work with-

PyTorch is another library function of Python, which is mainly used for Machine Learning. It is easy to use and efficient, thanks to an easy and fast scripting language, LuaJIT, and an underlying C/CUDA implementation

- torch.as_strided
- torch.heaviside
- torch.bernoulli
- torch.eig
- torch.pinverse

Before we begin, let's install and import PyTorch

In [274]:
# Import torch and other required modules
import torch

## Function 1 - torch.as_strided

"Stride" in English vocabulary means "steps" or "jumps", so if suppose we want to print some of the elements within a tensor which is at a regular interval of suppose 2 or any other number, we will use this function.

In [275]:
# Example 1 - 
#Taking random values for our tensor "a" of size 3x3
a = torch.randn(3,3)
a

tensor([[-0.6512, -1.5664,  0.5275],
        [ 0.9953,  1.1550, -0.3242],
        [ 1.2212, -0.4989, -1.7724]])

In [276]:
#Now, using the as_strided function
strided_a = torch.as_strided(a,(2,2),(1,2))
strided_a

tensor([[-0.6512,  0.5275],
        [-1.5664,  0.9953]])

#### Explanation -
Here the parameteres needs explanations-
i) First parameter is "input", the input tensor on which we want to apply our function! In this case it is tensor "a".
ii)Second parameter is "Size", detemining what will the size of the output tensor.
iii)Third parameter is "stride", which is the important part! Which is explained as below-


    >>> 1 reffers to the number of steps it will jump, that will be displayed verically in the output tensor
    >>> 2 reffers to the number of steps it will jump, that will be displayed horizontally(on side) in 
    the output tensor
 Important - The jumping of steps will never be vertical, it will always be with the side-by-side input tensor elements

In [277]:
# Example 2 - initializing the tensor
b = torch.randn(4,4)
b

tensor([[-0.7899,  0.0597,  0.9107,  0.0756],
        [ 0.9416,  0.4180, -1.6963,  0.9798],
        [ 1.9754,  1.6601, -1.0174,  0.1950],
        [-1.0024,  1.5864, -0.3588,  0.9624]])

In [278]:
#as_strided application
strided_b = torch.as_strided(b,(3,2),(1,3),2) 
strided_b

tensor([[ 0.9107,  0.4180],
        [ 0.0756, -1.6963],
        [ 0.9416,  0.9798]])

#### Explanantion -
Here there is an addition of another parameter and that is "storage_offset", means from which index position the tensor will be starting it's striding operation. For example, here we have provided with the value "2", thus our output tensor started from the value which is at index position 2. (Reminder - the indexing starts from 0)

In [279]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.tensor([[1,0,6],
                 [4,5,7],
                 [0,2,3]])
strided_c = torch.as_strided(c,(2,2),(3,1),5)
strided_c

RuntimeError: setStorage: sizes [2, 2], strides [3, 1], storage offset 5, and itemsize 8 requiring a storage size of 40 are out of bounds for storage of size 72

#### Error -
Here we get an error, because we have set our "storage_offset" value as 5, which means our output tensor's first value will be starting with the value which is at 5th position in the input tensor, which is 7 and clearly if we try to jump 3 steps, we do not have any value, thus it gives an error, as it runs out of memory.

#### Uses -
This function is to be used when we want to create a view of an existing torch.Tensor input with specified size, stride and storage_offset.

Let's save our work using Jovian before continuing.

In [280]:
!pip install jovian --upgrade --quiet

In [281]:
import jovian

In [282]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sathi-satb/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sathi-satb/01-tensor-operations


'https://jovian.ai/sathi-satb/01-tensor-operations'

## Function 2 - torch.heaviside

This function is commonly used in the mathematics of control theory and signal processing which represents a signal that switches on at a specified time and stays switched on indefinitely.

In [283]:
# Example 1 - 
input = torch.tensor([4.0,-1.8,0])
values_provided = torch.tensor([4.2])
torch.heaviside(input,values_provided)

tensor([1.0000, 0.0000, 4.2000])

#### Explanation-
Briefly, Heaviside is a discontinious function that will give us output in following manner -


    >>> if any of the input value is less than 0(input<0), it will return with the value 0 in output tensor.
    >>> if any of the input value is equal to 0(input==0), it will return with the value that we have provided
    in the parameter "values_provided"(values), in the output tensor.
    >>> if any of the input value is greater than 0(input>0), it will return with the value 1 in output tensor.

In [284]:
# Example 2 - working
input = torch.tensor([0,2.0,-1])
values = torch.tensor([9,4.0,7],)
torch.heaviside(input,values)

tensor([9., 1., 0.])

#### Explanation-
Here we apply it with the function with corresponding elements of "input" and "values" parameter having same dtype.

In [285]:
# Example 3 - breaking 
input = torch.tensor([0,-1,0])
values = torch.tensor([1,4.2,7])
torch.heaviside(input,values)

RuntimeError: heaviside is not yet implemented for tensors with different dtypes.

#### Error- 
We seen an error here as the data type of the corresponding elements does not match. in "input" parameter, -1 has dtype of int whereas in "values" parameter we have it's corresponding element as 4.2, thus it gives an error.

#### Uses -
Heaviside is mainly used in Biochemistry or Neuroscience department to approximate binary cellular switches in response to chemical signals.

In [286]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sathi-satb/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sathi-satb/01-tensor-operations


'https://jovian.ai/sathi-satb/01-tensor-operations'

## Function 3 - torch.bernoulli

Briefly, Bernoulli is a discrete probability distribution of a random variable ranging between 0 to 1. The output tensor only has values 0 or 1 and is of the same shape as input.

In [287]:
# Example 1 - working
d = torch.empty(3, 3).uniform_(0,1)
print(d)
torch.bernoulli(d)

tensor([[0.3431, 0.2680, 0.0725],
        [0.3789, 0.9373, 0.1668],
        [0.2437, 0.9880, 0.5082]])


tensor([[1., 0., 0.],
        [0., 1., 0.],
        [1., 1., 1.]])

#### Explanation-
By rule,the i th element of the output tensor will draw a value,according to the i th probability value given in input.
Simple,


  a) If we have a value that is 0.873, which is closer to 1, thus there will be maximum chance to get 
  1 as it's probable output.
  
  
  b) Again if we have a value like 0.32, which is closer to 0, will give output as 0 in maximum cases, as it's 
  probable output.

In [288]:
# Example 2 - This time we are focusing on a single element of a tensor and check it's probable outcomes 10 times.
e = torch.distributions.Bernoulli(torch.tensor([0.85])) #having 85% chance of giving output 1 and 15% chance of giving 0.

In [289]:
e.sample()

tensor([1.])

In [290]:
e.sample()

tensor([1.])

In [291]:
e.sample()

tensor([0.])

In [292]:
e.sample()

tensor([1.])

In [293]:
e.sample()

tensor([0.])

In [294]:
e.sample()

tensor([1.])

In [295]:
e.sample()

tensor([1.])

In [296]:
e.sample()

tensor([1.])

In [297]:
e.sample()

tensor([1.])

In [298]:
e.sample()

tensor([1.])

#### Explanation- 
This example gives more detailed idea about the probability distribution of Bernoulli. Where we passed the value 0.83, which is close to 1. When we passed the sample, we got "1" 8(or 9, as it may change every time we run the cell) times and "0" 2 times, which approximately comes down to 85% chance of getting output as 1.


NOTE - To get exactly 85% and 15% of probability distribution, we need to sample this a large number of times.

In [299]:
# Example 3 - breaking (to illustrate when it breaks)
f = torch.empty(3, 3).uniform_(0,2)
print(f)
torch.bernoulli(f)

tensor([[1.9048, 1.1839, 0.4503],
        [0.8419, 1.1032, 0.7527],
        [0.3788, 0.4506, 1.0344]])


RuntimeError: Expected p_in >= 0 && p_in <= 1 to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)

#### Explanation -
The range of the input tensor should be in range of [0,1],else the whole Bernoulli distribution, itself becomes wrong!

#### Uses-
It can be used in experiments and clinical trials, it is also sometimes used to model a single individual experiencing an event like death, a disease, or disease exposure.

In [300]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sathi-satb/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sathi-satb/01-tensor-operations


'https://jovian.ai/sathi-satb/01-tensor-operations'

## Function 4 - torch.eig

This function is used for evaluating Eigen values and it's vectors too, if required!

In [301]:
# Example 1 - working
a1 = torch.randn(3,3)
print(a)
a2 = torch.eig(a1)
a2

tensor([[-0.6512, -1.5664,  0.5275],
        [ 0.9953,  1.1550, -0.3242],
        [ 1.2212, -0.4989, -1.7724]])


torch.return_types.eig(
eigenvalues=tensor([[-1.7583,  0.0000],
        [ 0.2357,  0.0000],
        [ 1.3545,  0.0000]]),
eigenvectors=tensor([]))

#### Explanation -
We take random values for our tensor a1 and try to find it's eigen values.

In [302]:
# Example 2 - working
a2 = torch.eig(a1,eigenvectors=True)
a2

torch.return_types.eig(
eigenvalues=tensor([[-1.7583,  0.0000],
        [ 0.2357,  0.0000],
        [ 1.3545,  0.0000]]),
eigenvectors=tensor([[ 0.3818, -0.9372,  0.8645],
        [ 0.0483,  0.3177,  0.4766],
        [ 0.9230,  0.1440, -0.1598]]))

#### Explanation- 
We pass an extra boolean parameter,i.e. "eigenvectors", which when passed with True value, returns the Eigen vectors along with the Eigen values.

In [303]:
# Example 3 - breaking (to illustrate when it breaks)
b1 = torch.randn(2,3)
print(b1)
b2 = torch.eig(b1)

tensor([[ 0.1071,  0.0816,  1.1261],
        [ 0.3284, -0.4699,  1.1621]])


RuntimeError: invalid argument 1: A should be square at /pytorch/aten/src/TH/generic/THTensorLapack.cpp:207

#### Explanation-
For finding out Eigen values and it's vectors, the shape of the tensor should be square, else it will give an error!

#### Uses -
It is mainly used in control theory, vibration analysis, electric circuits, advanced dynamics and quantum
mechanics are just a few of the application areas.

In [304]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sathi-satb/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sathi-satb/01-tensor-operations


'https://jovian.ai/sathi-satb/01-tensor-operations'

## Function 5 - torch.pinverse

This function is used for finding out pseudo-inverse of a 2D tensor.

In [305]:
# Example 1 - working
x = torch.randn(3,3)
print(x)
torch.pinverse(x)

tensor([[ 1.0875,  1.2412, -0.8526],
        [ 0.8177, -0.8936, -0.5588],
        [-0.9564, -0.0929,  2.0549]])


tensor([[ 0.7039,  0.9214,  0.5426],
        [ 0.4272, -0.5291,  0.0334],
        [ 0.3469,  0.4049,  0.7407]])

#### Explanation-
We are initilaizing a 3X3 tensor having random values and then finding it's unique pseudo inverse of the tensor x.

In [306]:
# Example 2 - working
y = torch.randn(1,3,2)
print(y)
torch.pinverse(y)

tensor([[[-0.0822, -1.6779],
         [-0.5807,  0.1936],
         [ 0.0857,  0.1387]]])


tensor([[[-0.1720, -1.6623,  0.2393],
         [-0.5820,  0.0890,  0.0452]]])

#### Explanation-
In this case pinverse function is applied in a batch, that's the only difference here.

In [307]:
# Example 3 - breaking (to illustrate when it breaks)
z = torch.tensor([[1,2,3],
                 [4,5,6]])
torch.pinverse(z)

RuntimeError: pinverse(Long{[2, 3]}): expected a tensor with 2 or more dimensions of floating types

#### Explanation- 
In this case we are not taking random values are manually inserted, but here the problem arises due to the dtype of the input tensor! For evaluating pseudo inverse of a tensor, the input tensor always needs to be of dtype: float , 'int' dtype is not supported.

#### Uses-
It is widely used for  computing a "best fit" (least squares) solution to a system of linear equations that lacks a solution.

In [308]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sathi-satb/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sathi-satb/01-tensor-operations


'https://jovian.ai/sathi-satb/01-tensor-operations'

## Conclusion

This project helped in knowing 5 of the interesting functions realted to PyTorch Tensor library, among which most of them are used for higher level of calculation and studies.
It included two working examples of each function and one example when it gives an error.

Next thing to be done is to find more of such interesting PyTorch Library function and to understand them and potrat them in another notebook.

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* For knowing more about Heaviside function - https://mathworld.wolfram.com/HeavisideStepFunction.html
* For knowing more about Bernoulli Distribution - https://www.statisticshowto.com/bernoulli-distribution/
* For knowing more about Eigen Values and Eigen vectors - https://www.mathsisfun.com/algebra/eigenvalue.html
* For knowing more about The Moore-Penrose Pseudoinverse - https://www.math.ucla.edu/~laub/33a.2.12s/mppseudoinverse.pdf

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
