> ### Assignment Instructions (delete this cell before submission)
> 
> The objective of this assignment is to develop a solid understanding of PyTorch tensors. In this assignment you will:
>
> 1. Pick 5 interesting functions related to PyTorch tensors by [reading the documentation](https://pytorch.org/docs/stable/torch.html), 
> 2. Edit this starter template notebook to illustrate their usage and publish your notebook to Jovian using `jovian.commit`. Make sure to add proper explanations too, not just code.
> 3. Submit the link to your published notebook on Jovian here: https://jovian.ai/learn/deep-learning-with-pytorch-zero-to-gans/assignment/assignment-1-all-about-torch-tensor .
> 4. (Optional) Write a blog post on [Medium](https://medium.com) to accompany and showcase your Jupyter notebook. [Embed cells from your notebook](https://medium.com/@aakashns/share-and-embed-jupyter-notebooks-online-with-jovian-ml-df709a03064e) wherever necessary.
> 5. (Optional) [Share your work](https://jovian.ai/forum/t/pytorch-functions-and-tensor-operations/13790) with the community and exchange feedback with other participants
>
>
> The recommended way to run this notebook is to click the "Run" button at the top of this page, and select "Run on Colab". Run `jovian.commit` regularly to save your progress.
> 
> Try to give your notebook an interesting title e.g. "All about PyTorch tensor operations", "5 PyTorch functions you didn't know you needed", "A beginner's guide to Autograd in PyToch", "Interesting ways to create PyTorch tensors", "Trigonometic functions in PyTorch", "How to use PyTorch tensors for Linear Algebra" etc.
>
> **IMPORTANT NOTE**: Make sure to submit a Jovian notebook link e.g. https://jovian.ai/aakashns/01-tensor-operations . Colab links will not be accepted.
>
> Remove this cell containing instructions before making a submission or sharing your notebook, to make it more presentable.
>



# Title Here

An short introduction about PyTorch and about the chosen functions. 

- as_strided
- function 2
- function 3
- function 4
- function 5

Before we begin, let's install and import PyTorch

In [87]:
# Uncomment and run the appropriate command for your operating system, if required

# Linux / Binder
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# Windows
# !pip install numpy torch==1.7.0+cpu torchvision==0.8.1+cpu torchaudio==0.7.0 -f https://download.pytorch.org/whl/torch_stable.html

# MacOS
# !pip install numpy torch torchvision torchaudio

In [88]:
# Import torch and other required modules
import torch

## Function 1 - torch.as_strided

"Stride" in English vocabulary means "steps" or "jumps", so if suppose we want to print some of the elements within a tensor which is at a regular interval of suppose 2 or any other number, we will use this function

In [101]:
# Example 1 - 
#Taking random values for our tensor "a" of size 3x3
a = torch.randn(3,3)
a

tensor([[-1.8014,  1.3771,  0.0968],
        [ 1.2616, -0.3182, -2.6834],
        [ 0.8921,  0.7615,  0.3717]])

In [102]:
#Now, using the as_strided function
strided_a = torch.as_strided(a,(2,2),(1,2))
strided_a

tensor([[-1.8014,  0.0968],
        [ 1.3771,  1.2616]])

#### Explanation -
Here the parameteres needs explanations-
i) First parameter is "input", the input tensor on which we want to apply our function! In this case it is tensor "a".
ii)Second parameter is "Size", detemining what will the size of the output tensor.
iii)Third parameter is "stride", which is the important part! Which is explained as below-


    >>> 1 reffers to the number of steps it will jump, that will be displayed verically in the output tensor
    >>> 2 reffers to the number of steps it will jump, that will be displayed horizontally(on side) in the output tensor
 Important - The jumping of steps will never be vertical, it will always be with the side-by-side input tensor elements

In [103]:
# Example 2 - initializing the tensor
b = torch.randn(4,4)
b

tensor([[ 0.7089, -1.4291,  0.1969, -1.2583],
        [ 1.6609,  0.2315,  1.0490,  0.6413],
        [-0.1616,  0.3568, -1.2592,  1.0591],
        [-0.4346, -0.5656,  0.2357, -0.2978]])

In [104]:
#as_strided application
strided_b = torch.as_strided(b,(3,2),(1,3),2) 
strided_b

tensor([[ 0.1969,  0.2315],
        [-1.2583,  1.0490],
        [ 1.6609,  0.6413]])

#### Explanantion -
Here there is an addition of another parameter and that is "storage_offset", means from which index position the tensor will be starting it's striding operation. For example, here we have provided with the value "2", thus our output tensor started from the value which is at index position 2. (Reminder - the indexing starts from 0)

In [105]:
# Example 3 - breaking (to illustrate when it breaks)
c = torch.tensor([[1,0,6],
                 [4,5,7],
                 [0,2,3]])
strided_c = torch.as_strided(c,(2,2),(3,1),5)
strided_c

RuntimeError: setStorage: sizes [2, 2], strides [3, 1], storage offset 5, and itemsize 8 requiring a storage size of 40 are out of bounds for storage of size 72

#### Error -
Here we get an error, because we have set our "storage_offset" value as 5, which means our output tensor's first value will be starting with the value which is at 5th position in the input tensor, which is 7 and clearly if we try to jump 3 steps, we do not have any value, thus it gives an error, as it runs out of memory.

#### Working -
This function is to be used when we want to create a view of an existing torch.Tensor input with specified size, stride and storage_offset.

Let's save our work using Jovian before continuing.

In [106]:
!pip install jovian --upgrade --quiet

In [107]:
import jovian

In [108]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "sathi-satb/01-tensor-operations" on https://jovian.ai
[jovian] Uploading notebook..
[jovian] Uploading additional files...
[jovian] Committed successfully! https://jovian.ai/sathi-satb/01-tensor-operations


'https://jovian.ai/sathi-satb/01-tensor-operations'

## Function 2 - ???

Add some explanations

In [6]:
# Example 1 - working

Explanation about example

In [7]:
# Example 2 - working

Explanation about example

In [8]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [16]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 3 - ???

Add some explanations

In [9]:
# Example 1 - working

Explanation about example

In [10]:
# Example 2 - working

Explanation about example

In [11]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [17]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 4 - ???

Add some explanations

In [12]:
# Example 1 - working

Explanation about example

In [13]:
# Example 2 - working

Explanation about example

In [14]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [18]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Function 5 - ???

Add some explanations

In [14]:
# Example 1 - working

Explanation about example

In [15]:
# Example 2 - working

Explanation about example

In [16]:
# Example 3 - breaking (to illustrate when it breaks)

Explanation about example

Closing comments about when to use this function

In [19]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
[jovian] Updating notebook "aakashns/01-tensor-operations" on https://jovian.ai/
[jovian] Uploading notebook..
[jovian] Capturing environment..
[jovian] Committed successfully! https://jovian.ai/aakashns/01-tensor-operations


'https://jovian.ai/aakashns/01-tensor-operations'

## Conclusion

Summarize what was covered in this notebook, and where to go next

## Reference Links
Provide links to your references and other interesting articles about tensors
* Official documentation for tensor operations: https://pytorch.org/docs/stable/torch.html
* ...

In [ ]:
jovian.commit(project='01-tensor-operations')

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
